/**
 * Specialized Agent Types - Shared interfaces for specialized agent services
 */

import { AgentType } from '@prisma/client';

/**
 * Context for agent conversations
 */
export interface AgentContext {
  agentId: string;
  organizationId: string;
  leadId?: string;
  phone: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  conversationHistory: Array<{ role: string; content: string }>;
  metadata?: Record<string, any>;
}

/**
 * Standard response from an agent
 */
export interface AgentResponse {
  message: string;
  action?: string;
  data?: Record<string, any>;
  shouldEnd?: boolean;
  nextAgent?: AgentType;
}

/**
 * Quote generated by sales agent
 */
export interface QuoteData {
  id: string;
  leadId?: string;
  products: Array<{ name: string; price: number; quantity: number }>;
  subtotal: number;
  discount: number;
  total: number;
  validUntil: Date;
  createdAt: Date;
}

/**
 * Available appointment slot
 */
export interface AppointmentSlot {
  date: string;
  times: string[];
}

/**
 * Pending payment info
 */
export interface PendingPayment {
  id: string;
  amount: number;
  dueDate: string;
}

/**
 * Support ticket
 */
export interface SupportTicket {
  id: string;
  leadId?: string;
  category: string;
  priority: string;
  description: string;
  status: string;
  createdAt: Date;
}

/**
 * Handoff messages between agents
 */
export const HANDOFF_MESSAGES: Record<AgentType, string> = {
  VOICE: "I'll connect you with our voice assistant.",
  SALES: "Let me connect you with our sales specialist who can help you further.",
  APPOINTMENT: "I'll help you schedule an appointment now.",
  PAYMENT: "Let me assist you with the payment process.",
  SUPPORT: "I'm transferring you to our support team.",
  FOLLOWUP: "We'll be in touch with you soon.",
  SURVEY: "I'd love to get your feedback on your experience.",
};
